# Single-node k3s cluster. The VM is created by scripts/pve-create-vm.sh (cloud-init),
# everything after first boot is done by Ansible.
all:
  children:
    k3s_nodes:
      hosts:
        k3s01:
          ansible_host: 10.2.1.20
