// Package ruleindex says where in the repository the rules and policies a scenario runs into are
// defined: the Falco rule that detects it, the Falco Talon rule that answers it, and the admission
// and network policies every sandbox pod is subject to (ADR 0021). The page links each one to
// github.com/HubertMJ/self-defending-portfolio/blob/<commit>/<file>#L<line>, so a visitor can read
// the exact rule that fired, at the exact commit the API was built from.
//
// The data is index.json, generated by scripts/gen-rule-index.sh from cluster/ and embedded at build
// time: the API image is built from app/api alone and has no copy of cluster/. The unit test checks
// every entry against the files whenever it runs inside a full checkout.
package ruleindex

import (
	_ "embed"
	"encoding/json"
)

//go:embed index.json
var indexJSON []byte

// Rule is a rule's name and where it is defined. File is empty for a Falco rule that ships with the
// Falco image (a stock rule) rather than living in this repository.
type Rule struct {
	Name string `json:"name"`
	File string `json:"file"`
	Line int    `json:"line"`
}

// Policy is an admission or network policy that applies to sandbox pods.
type Policy struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
	File string `json:"file"`
}

type location struct {
	Name string `json:"name"`
	File string `json:"file"`
	Line int    `json:"line"`
}

// Index is the parsed index.json.
type Index struct {
	Falco    map[string]location `json:"falco"`    // by Falco rule name
	Talon    map[string]location `json:"talon"`    // by the Falco rule name the Talon rule matches
	Policies []Policy            `json:"policies"` // in file order
}

// Load parses the embedded index. It fails only if the file is not valid JSON, which the unit test
// rules out.
func Load() (*Index, error) {
	var ix Index
	if err := json.Unmarshal(indexJSON, &ix); err != nil {
		return nil, err
	}
	return &ix, nil
}

// FalcoRule is the Falco rule called name; its file is empty for a stock rule.
func (ix *Index) FalcoRule(name string) Rule {
	l := ix.Falco[name]
	return Rule{Name: name, File: l.File, Line: l.Line}
}

// TalonRule is the Talon rule that answers the Falco rule called falcoRule, or a zero Rule if none
// does.
func (ix *Index) TalonRule(falcoRule string) Rule {
	l, ok := ix.Talon[falcoRule]
	if !ok {
		return Rule{}
	}
	return Rule(l)
}
